"""
This type stub file was generated by Claude from
from https://brentp.github.io/cyvcf2/docstrings.html
"""

from typing import Any, Iterator, Optional, Union

import numpy as np

class INFO:
    """
    INFO is created internally by accessing Variant.INFO.

    Acts like a dictionary where keys are expected to be in the INFO
    field of the Variant and values are typed according to what is
    specified in the VCF header.

    Items can be deleted with `del v.INFO[key]` and accessed with
    `v.INFO[key]` or `v.INFO.get(key)`.
    """

    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def __iter__(self) -> Iterator[tuple[str, Any]]: ...

class Variant:
    """
    Variant represents a single VCF Record.

    Created internally by iterating over a VCF.
    """

    INFO: INFO
    POS: int
    ALT: list[str]
    CHROM: str
    FILTER: Optional[str]
    FILTERS: list[str]
    FORMAT: list[str]
    ID: Optional[str]
    QUAL: Optional[float]
    REF: str

    aaf: float
    call_rate: float
    end: int
    genotypes: list[list[Union[int, bool]]]

    gt_alt_depths: np.ndarray
    gt_alt_freqs: np.ndarray
    gt_bases: np.ndarray
    gt_depths: np.ndarray
    gt_phases: np.ndarray
    gt_phred_ll_het: np.ndarray
    gt_phred_ll_homalt: np.ndarray
    gt_phred_ll_homref: np.ndarray
    gt_quals: np.ndarray
    gt_ref_depths: np.ndarray
    gt_types: np.ndarray

    is_deletion: bool
    is_indel: bool
    is_mnp: bool
    is_snp: bool
    is_sv: bool
    is_transition: bool

    num_called: int
    num_het: int
    num_hom_alt: int
    num_hom_ref: int
    num_unknown: int

    ploidy: int
    start: int
    var_type: str

    def format(self, field: str, vtype: Optional[type] = ...) -> np.ndarray:
        """
        Return a numpy array for the requested FORMAT field.

        The numpy array shape will match the requested field, e.g. if
        the field has number=3, the shape will be (n_samples, 3).
        """
        ...

    def set_format(self, name: str, data: np.ndarray) -> None:
        """
        Set the FORMAT field given by name.

        data must be a numpy array of type float, int, or fixed-length
        ASCII string (np.bytes_).
        """
        ...

    def set_pos(self, pos0: int) -> None:
        """Set the POS to the given 0-based position."""
        ...

class VCF:
    """
    VCF class holds methods to iterate over and query a VCF.
    """

    samples: list[str]
    seqlens: list[int]
    seqnames: list[str]
    raw_header: str

    def __init__(
        self,
        fname: str,
        mode: str = "r",
        gts012: bool = False,
        lazy: bool = False,
        strict_gt: bool = False,
        samples: Optional[list[str]] = None,
        threads: Optional[int] = None,
    ) -> None: ...
    def __iter__(self) -> Iterator[Variant]: ...
    def __next__(self) -> Variant: ...
    def __call__(self, region: str) -> Iterator[Variant]: ...
    def add_filter_to_header(self, adict: dict[str, Any]) -> None:
        """Add a FILTER line to the VCF header. adict needs ID, Description."""
        ...

    def add_format_to_header(self, adict: dict[str, Any]) -> None:
        """Add a FORMAT line to the VCF header. adict needs ID, Number, Type, Description."""
        ...

    def add_info_to_header(self, adict: dict[str, Any]) -> None:
        """Add an INFO line to the VCF header. adict needs ID, Number, Type, Description."""
        ...

    def add_to_header(self, line: str) -> None:
        """Add a new raw line to the VCF header."""
        ...

    def contains(self, id: str) -> bool:
        """Check if the given ID is in the header."""
        ...

    def gen_variants(
        self,
        sites: Any,
        offset: int = 0,
        each: int = 1,
        call_rate: float = 0.8,
    ) -> Iterator[Variant]: ...
    def get_header_type(
        self,
        key: str,
        order: list[int] = ...,
    ) -> dict[str, Any]:
        """Extract a field from the VCF header by id. Returns a dict."""
        ...

    def header_iter(self) -> Iterator[Any]:
        """Iterate over fields in the HEADER."""
        ...

    def relatedness(
        self,
        n_variants: int = 35000,
        gap: int = 30000,
        min_af: float = 0.04,
        max_af: float = 0.8,
        linkage_max: float = 0.2,
        min_depth: int = 8,
    ) -> Any: ...
    def set_index(self, index_path: str = "") -> None: ...
    def set_samples(self, samples: list[str]) -> None:
        """
        Set the samples to be pulled from the VCF.

        Must be called before any iteration.
        """
        ...

class Writer:
    """
    Writer class makes a VCF Writer.
    """

    name: bytes

    def __init__(
        self,
        fname: str,
        tmpl: VCF,
        mode: Optional[str] = None,
    ) -> None:
        """
        mode: if None (default), inferred from the filename extension.
        If fname == "-" (stdout) and mode is left at default, uncompressed
        VCF is produced. Valid values:
            "wbu": uncompressed BCF
            "wb":  compressed BCF
            "wz":  compressed VCF
            "w":   uncompressed VCF
        A compression level can be appended to compressed modes,
        e.g. "wz4".
        """
        ...

    def close(self) -> None: ...
    @classmethod
    def from_string(
        cls,
        fname: str,
        header_string: str,
        mode: str = "w",
    ) -> "Writer": ...
    def variant_from_string(self, variant_string: str) -> Variant: ...
    def write_header(self) -> None: ...
    def write_record(self, var: Variant) -> None:
        """Write the variant to the writer."""
        ...
