name: "python module's tests"
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  formatting:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/flake_init
      - run: nix develop --accept-flake-config -c -- make format-check

  lint_type_checks:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/flake_init
      - run: nix develop --accept-flake-config -c -- make python_checks

  tests:
    runs-on: ubuntu-slim
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/flake_init
      - run: nix develop --accept-flake-config -c -- make tests

  nix_build_test:
    runs-on: ubuntu-slim
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - run: nix build .\#deepgenocompress

  build-docs:
    # needs: [tests] # TODO: uncomment once test job is fixed
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - uses: ./.github/actions/flake_init
      - run: nix develop --accept-flake-config -c -- make doc
      - uses: actions/configure-pages@v5
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      - uses: actions/upload-pages-artifact@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          path: docs/_build/html

  deploy-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [build-docs]
    runs-on: ubuntu-slim
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

