name: "python module's tests"
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - run: nix develop --accept-flake-config -c -- make format-check

  lint_type_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - run: nix develop --accept-flake-config -c -- make python_checks

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - run: nix develop --accept-flake-config -c -- make tests

  deploy-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [tests]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/nix-setup
      - run: nix develop --accept-flake-config -c -- make doc
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html
      - id: deployment
        uses: actions/deploy-pages@v4

