name: "python module's tests"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/nix-setup
      - run: nix develop --accept-flake-config -c -- make format-check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/nix-setup
      - run: nix develop --accept-flake-config -c -- make tests

